import { useEffect, useRef, useState } from 'react';
import { elementBySymbol } from '../data/elementData';
import { buildLewisStructure } from '../engine/lewisEngine';
import { formatChemicalFormula } from '../engine/formatting';
import { getCompatibleElements, validateReaction } from '../engine/reactionEngine';
import type { Atom, ReactionResult } from '../types/chemistry';
import PeriodicTable from './chemsim/PeriodicTable';
import LewisStructureView from './chemsim/LewisStructureView';

const colors:Record<string,string> = { metal:'#f3a63b', nonmetal:'#8c72e8', 'noble gas':'#59bfc5' };
export default function ChemSim() {
  const [atoms,setAtoms]=useState<Atom[]>([]);
  const [selectedSymbol,setSelectedSymbol]=useState<string>();
  const [result,setResult]=useState<ReactionResult>({valid:false,reactants:[],products:[],feedback:'Choose an element from the periodic table, then analyze your selection.'});
  const [history,setHistory]=useState<string[]>([]);
  const [seconds,setSeconds]=useState(15);
  const [expired,setExpired]=useState(false);
  const [showBond,setShowBond]=useState(false);
  const [tab,setTab]=useState<'Compound'|'Shell Sim'|'Lewis'|'How?'|'Analysis'>('Compound');
  const canvas=useRef<HTMLCanvasElement>(null);
  const reduced=useRef(matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{ const tick=()=>{ const c=canvas.current, ctx=c?.getContext('2d'); if(!c||!ctx)return; const w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=c.clientHeight;ctx.clearRect(0,0,W,H);ctx.fillStyle='#f9f7ff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#d9d2ef';for(let x=18;x<W;x+=20)for(let y=18;y<H;y+=20)ctx.fillRect(x,y,1,1);atoms.forEach((atom,index)=>{const x=atom.x||W/2+(index-(atoms.length-1)/2)*95,y=atom.y||H/2;const bob=reduced.current?0:Math.sin(Date.now()/650+index)*3;ctx.beginPath();ctx.arc(x,y+bob,35,0,Math.PI*2);ctx.fillStyle=colors[atom.element.category]??'#8c72e8';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(atom.element.symbol,x,y+bob+6);ctx.font='10px system-ui';ctx.fillText(String(atom.element.atomicNumber),x,y+bob-43);for(let i=0;i<atom.element.valenceElectrons;i++){const a=(Math.PI*2*i)/Math.max(atom.element.valenceElectrons,1);ctx.beginPath();ctx.arc(x+48*Math.cos(a),y+bob+48*Math.sin(a),3.5,0,Math.PI*2);ctx.fillStyle='#44365f';ctx.fill();}});requestAnimationFrame(tick);};const id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[atoms]);
  useEffect(()=>{if(!atoms.length||result.valid||seconds<=0)return;const id=window.setTimeout(()=>{if(seconds===1){setSeconds(0);setExpired(true)}else setSeconds(s=>s-1)},1000);return()=>clearTimeout(id)},[seconds,atoms.length,result.valid]);
  const add=(symbol:string)=>{const e=elementBySymbol(symbol);if(!e)return;if(!atoms.length)setSeconds(15);setExpired(false);setAtoms(a=>[...a,{id:crypto.randomUUID(),element:e,x:0,y:0,state:'idle'}]);setResult({valid:false,reactants:[],products:[],feedback:`${e.name} added. Build a precise reactant group, then select Analyze.`})};
  const analyze=()=>{const r=validateReaction(atoms.map(a=>a.element.symbol));setResult(r);if(r.valid&&r.formula){setHistory(h=>[r.formula!,...h].slice(0,8));setShowBond(true);}};
  const lewis=buildLewisStructure(result);
  return <main className="sim-shell">
    <section className="palette card"><PeriodicTable selectedSymbol={selectedSymbol} onSelect={element=>setSelectedSymbol(element.symbol)} onAdd={add}/></section>
    <section className="workspace card" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const symbol=event.dataTransfer.getData('text/plain');if(symbol)add(symbol)}}><div className="section-title"><div><span className="eyebrow">BONDING WORKSPACE</span><h2>Build a reaction</h2></div><div className="timer" aria-label="Bonding timer">{seconds}s</div></div><canvas ref={canvas} aria-label="Animated atom workspace" onDoubleClick={()=>setAtoms(a=>a.slice(0,-1))}/><p className="canvas-note">Drag elements here, or click a tile to add it. Double-click the workspace to remove the latest atom.</p><div className="tray">{atoms.length?atoms.map((a,i)=><button key={a.id} onClick={()=>setAtoms(all=>all.filter((_,n)=>n!==i))}>{a.element.symbol} <span>×</span></button>):<span>Atoms will appear here</span>}</div><div className="controls"><button className="secondary" onClick={()=>{setAtoms([]);setResult({valid:false,reactants:[],products:[],feedback:'Workspace cleared.'})}}>Clear</button><button className="primary" onClick={analyze}>Analyze &amp; bond</button></div></section>
    <aside className="analysis card"><span className="eyebrow">REACTION ANALYSIS</span><h2>{result.formula?formatChemicalFormula(result.formula):'Ready to explore'}</h2><div className={result.valid?'status success':'status'}>{result.feedback??(result.valid?'Reaction complete.':'Awaiting analysis.')}</div>{result.valid&&<><dl><dt>Compound</dt><dd>{result.compoundName}</dd><dt>Bond model</dt><dd>{result.bondType}</dd><dt>Geometry</dt><dd>{result.geometry}</dd><dt>Polarity</dt><dd>{result.polarity}</dd></dl><div className="lewis"><strong>Lewis structure</strong><small>{lewis.supported ? `${lewis.structure.totalValenceElectrons} valence electrons · ${lewis.structure.atoms.reduce((sum, atom) => sum + atom.lonePairCount, 0)} lone pairs` : lewis.reason}</small></div></>}<div className="suggestions"><strong>Compatible suggestions</strong><p>{atoms.length?getCompatibleElements(atoms[0].element.symbol).slice(0,8).join(' · '):'Add an atom to see guided partners.'}</p></div><div className="history"><strong>Reaction book</strong>{history.length?history.map((f,i)=><span key={i}>{formatChemicalFormula(f)}</span>):<p>No completed reactions yet.</p>}</div></aside>
  {expired&&<div className="overlay" role="dialog" aria-modal="true"><div className="modal"><button className="close" onClick={()=>setExpired(false)}>×</button><h2>Time Expired</h2><p>You ran out of time! Try again — you have 15 seconds to form a valid compound.</p><button className="primary" onClick={()=>{setSeconds(15);setExpired(false)}}>Retry Challenge</button><button className="secondary" onClick={()=>{setAtoms([]);setSeconds(15);setExpired(false)}}>Reset Workspace</button></div></div>}
  {showBond&&result.valid&&<div className="overlay" role="dialog" aria-modal="true"><div className="modal bond"><button className="close" onClick={()=>setShowBond(false)}>×</button><span className="eyebrow">BOND EXPLORER</span><h1>{formatChemicalFormula(result.formula!)}</h1><h2>{result.compoundName}</h2><div className="tabs">{(['Compound','Shell Sim','Lewis','How?','Analysis'] as const).map(item=><button className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==='Compound'&&<p><b>{result.bondType}</b> · {result.geometry}<br/>{result.polarity}<br/><br/>{result.explanation}</p>}{tab==='Lewis'&&<LewisStructureView result={lewis} geometry={result.geometry} />}{tab==='Shell Sim'&&<p>Atoms identified → valence electrons displayed → atoms approach → {result.animationType} → stable product.</p>}{tab==='How?'&&<p>{result.explanation} This shell model is educational, not a literal quantum-mechanical trajectory.</p>}{tab==='Analysis'&&<p>Bond type: {result.bondType}<br/>Geometry: {result.geometry}<br/>Molecular polarity: {result.polarity}<br/>Valence electrons: {lewis.supported ? lewis.structure.totalValenceElectrons : 'Unavailable'}</p>}</div></div>}
  </main>;
}
