import { useEffect, useState } from 'react';
import { createClassroom, getTeacherClassroom, listClassroomMembers, listTeacherClassrooms, setClassroomActive, updateClassroom } from '../lib/classrooms';
import { assignActivity, listClassroomAssignments, listTeacherActivities, removeActivityAssignment } from '../lib/quizService';
import type { ClassroomMemberProfile, QuizActivity, TeacherClassroom } from '../types/teacher';

export function TeacherClassroomManager({ path, navigate }: { path: string; navigate: (to: string) => void }) {
  const id = path.match(/^\/teacher\/classrooms\/([^/]+)$/)?.[1];
  const isNew = id === 'new';
  const [rooms, setRooms] = useState<TeacherClassroom[]>([]); const [room, setRoom] = useState<TeacherClassroom | null>(null);
  const [members, setMembers] = useState<ClassroomMemberProfile[]>([]); const [assignments, setAssignments] = useState<Array<Record<string, unknown>>>([]); const [activities, setActivities] = useState<QuizActivity[]>([]);
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [program, setProgram] = useState(''); const [year, setYear] = useState(''); const [section, setSection] = useState('');
  const [quizId, setQuizId] = useState(''); const [availableFrom, setAvailableFrom] = useState(''); const [dueAt, setDueAt] = useState(''); const [isPublished, setIsPublished] = useState(true);
  const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { setBusy(true); setError(''); try {
    const [classrooms, activityList] = await Promise.all([listTeacherClassrooms(), listTeacherActivities()]); setRooms(classrooms); setActivities(activityList);
    if (id && !isNew) { const [selected, students, assigned] = await Promise.all([getTeacherClassroom(id), listClassroomMembers(id), listClassroomAssignments(id)]); setRoom(selected); setName(selected.name); setDescription(selected.description ?? ''); setProgram(selected.program ?? ''); setYear(selected.year_level ?? ''); setSection(selected.section ?? ''); setMembers(students); setAssignments(assigned as unknown as Array<Record<string, unknown>>); } else setRoom(null);
  } catch (cause) { setError(cause instanceof Error ? cause.message : 'Classrooms could not be loaded.'); } finally { setBusy(false); } };
  useEffect(() => { void load(); }, [path]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const draft = { name, description, program, year_level: year, section }; const saved = room ? await updateClassroom(room.id, draft) : await createClassroom(draft); setRoom(saved); setMessage(room ? 'Classroom updated.' : 'Classroom created.'); navigate(`/teacher/classrooms/${saved.id}`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Classroom could not be saved.'); } finally { setSaving(false); } };
  const copyCode = async () => { if (!room) return; try { await navigator.clipboard.writeText(room.join_code); setMessage('Classroom code copied.'); } catch { setMessage(`Classroom code: ${room.join_code}`); } };
  const toggleRoom = async () => { if (!room) return; try { await setClassroomActive(room.id, !room.is_active); setMessage(`Classroom ${room.is_active ? 'deactivated' : 'activated'}.`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Classroom status could not be changed.'); } };
  const assign = async (event: React.FormEvent) => { event.preventDefault(); if (!room || !quizId) return; try { await assignActivity({ classroomId: room.id, quizId, availableFrom: availableFrom ? new Date(availableFrom).toISOString() : undefined, dueAt: dueAt ? new Date(dueAt).toISOString() : undefined, isPublished }); setQuizId(''); setAvailableFrom(''); setDueAt(''); setMessage('Activity assigned to classroom.'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Activity could not be assigned.'); } };
  const unassign = async (assignmentId: string) => { if (!window.confirm('Remove this activity from the classroom?')) return; try { await removeActivityAssignment(assignmentId); setMessage('Activity removed from classroom.'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Assignment could not be removed.'); } };
  const input = (label: string, value: string, setter: (v: string) => void) => <label><span>{label}</span><input value={value} onChange={event => setter(event.target.value)}/></label>;
  const form = <form className="builder-card classroom-form" onSubmit={save}><h2>{room ? 'Edit classroom' : 'Create classroom'}</h2>{input('Class name', name, setName)}<label><span>Description</span><textarea rows={3} value={description} onChange={event => setDescription(event.target.value)}/></label><div className="builder-two-col">{input('Program', program, setProgram)}{input('Year level', year, setYear)}</div>{input('Section', section, setSection)}<button className="primary" disabled={saving}>{saving ? 'Saving…' : room ? 'Save changes' : 'Create classroom'}</button></form>;
  if (busy) return <main className="teacher-builder-shell"><p role="status">Loading classrooms…</p></main>;
  return <main className="teacher-builder-shell"><div className="teacher-builder-topbar"><div><span className="eyebrow">TEACHER PORTAL</span><h1>{room?.name ?? (isNew ? 'Create classroom' : 'Classrooms')}</h1></div>{!isNew && <button className="primary" onClick={() => navigate('/teacher/classrooms/new')}>+ Create Classroom</button>}</div>
    {error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}
    {(!id || isNew) && <section className="classroom-list">{isNew && form}{rooms.map(item => <article className="classroom-row builder-card" key={item.id}><div><h2>{item.name}</h2><p>{[item.program,item.year_level,item.section].filter(Boolean).join(' · ') || 'Class details not set'}</p><strong>{item.join_code}</strong> · {item.is_active ? 'Active' : 'Inactive'}</div><button className="secondary" onClick={() => navigate(`/teacher/classrooms/${item.id}`)}>Open classroom</button></article>)}{!rooms.length && !isNew && <div className="empty-state-card"><h2>No classrooms yet</h2><p>Create a classroom to get a database-generated join code.</p></div>}</section>}
    {room && <><section className="builder-card"><div className="section-title"><div><span className="eyebrow">CLASS CODE</span><h2>{room.join_code}</h2><p>{[room.program,room.year_level,room.section].filter(Boolean).join(' · ')}</p><p>{room.description || 'No description provided.'}</p></div><div className="builder-actions"><button className="secondary" onClick={() => void copyCode()}>Copy Code</button><button className="secondary" onClick={() => void toggleRoom()}>{room.is_active ? 'Deactivate' : 'Activate'}</button><button className="secondary" onClick={() => navigate('/teacher/classrooms')}>All classrooms</button></div></div><p>{members.length} students · {assignments.length} activities · {room.is_active ? 'Active' : 'Inactive'}</p></section>{form}
      <section className="builder-card"><h2>Students ({members.length})</h2>{members.map((student: ClassroomMemberProfile) => <p className="classroom-member" key={student.id}><strong>{student.full_name || 'Student'}</strong><span>{[student.program,student.year_level,student.section].filter(Boolean).join(' · ')}</span></p>)}{!members.length && <p className="muted">No students have joined this classroom.</p>}</section>
      <section className="builder-card"><h2>Assigned activities ({assignments.length})</h2>{assignments.map(row => { const quiz = row.quiz as Record<string, unknown>; return <article className="activity-list-item" key={String(row.id)}><div><h3>{String(quiz?.title ?? 'Activity')}</h3><p>{String(quiz?.category ?? '')} · {String(quiz?.difficulty ?? '')} · {String(quiz?.total_questions ?? 0)} questions · {Math.round(Number(quiz?.time_limit_seconds ?? 0)/60)} min · {row.is_published ? 'Published' : 'Draft'}</p><p>{row.due_at ? `Due ${new Date(String(row.due_at)).toLocaleString()}` : 'No due date'}</p></div><button className="secondary" onClick={() => void unassign(String(row.id))}>Remove</button></article>; })}{!assignments.length && <p className="muted">No activities assigned.</p>}<form className="assignment-form" onSubmit={assign}><h3>Assign Activity</h3><label><span>Activity</span><select required value={quizId} onChange={event => setQuizId(event.target.value)}><option value="">Choose an activity</option>{activities.map(activity => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label><span>Available from (optional)</span><input type="datetime-local" value={availableFrom} onChange={event => setAvailableFrom(event.target.value)}/></label><label><span>Due date (optional)</span><input type="datetime-local" value={dueAt} onChange={event => setDueAt(event.target.value)}/></label><label className="toggle-row"><input type="checkbox" checked={isPublished} onChange={event => setIsPublished(event.target.checked)}/><span>Publish assignment</span></label><button className="primary">Assign Activity</button></form></section></>}
  </main>;
}
