import { useEffect, useState } from 'react';
import { assignActivity, deleteQuizActivity, listTeacherActivities, loadTeacherActivity, publishQuizActivity, saveQuizActivity } from '../lib/quizService';
import { listTeacherClassrooms } from '../lib/classrooms';
import type { ActivityCategory, ActivityDifficulty, QuizActivity, QuizQuestion, TeacherClassroom, TeacherQuestionType } from '../types/teacher';

const questionTypes: TeacherQuestionType[] = ['multiple_choice','true_false','short_answer','bond_type','identification','formula_completion'];
const freshQuestion = (order: number): QuizQuestion => ({ question_order: order, question_text: '', question_type: 'multiple_choice', options: ['Option 1','Option 2'], correct_answer: '', points: 1, hint: '', explanation: '' });
const freshActivity = (): QuizActivity => ({ title: '', description: '', instructions: '', category: 'general', difficulty: 'medium', time_limit_seconds: 900, is_published: false, total_questions: 0, questions: [] });

export function TeacherActivityBuilder({ path, navigate }: { path: string; navigate: (to: string) => void }) {
  const editId = path.match(/^\/teacher\/activities\/([^/]+)\/edit$/)?.[1];
  const isNew = path === '/teacher/activities/new';
  const isEditor = isNew || Boolean(editId);
  const [items, setItems] = useState<QuizActivity[]>([]); const [draft, setDraft] = useState<QuizActivity | null>(null);
  const [classrooms, setClassrooms] = useState<TeacherClassroom[]>([]); const [assigning, setAssigning] = useState<QuizActivity | null>(null); const [classroomId, setClassroomId] = useState(''); const [availableFrom, setAvailableFrom] = useState(''); const [dueAt, setDueAt] = useState(''); const [isPublished, setIsPublished] = useState(true);
  const [preview, setPreview] = useState(false); const [busy, setBusy] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { setBusy(true); setError(''); try { setItems(await listTeacherActivities()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Activities could not be loaded.'); } finally { setBusy(false); } };
  useEffect(() => { void load(); if (editId) void loadTeacherActivity(editId).then(setDraft).catch(cause => setError(cause instanceof Error ? cause.message : 'Activity could not be loaded.')); else if (isNew) setDraft(freshActivity()); else setDraft(null); }, [path]);
  const update = (key: keyof QuizActivity, value: QuizActivity[keyof QuizActivity]) => setDraft(current => current ? { ...current, [key]: value } : current);
  const updateQuestion = (index: number, key: keyof QuizQuestion, value: QuizQuestion[keyof QuizQuestion]) => setDraft(current => current ? { ...current, questions: current.questions.map((question, i) => i === index ? { ...question, [key]: value } : question) } : current);
  const save = async (publish = false) => { if (!draft) return; setSaving(true); setError(''); try { if (!draft.title.trim()) throw new Error('Enter an activity title.'); const result = publish ? await publishQuizActivity(draft) : await saveQuizActivity({ ...draft, is_published: false }); setDraft(result); setMessage(publish ? 'Activity published.' : 'Activity saved as draft.'); if (isNew && result.id) navigate(`/teacher/activities/${result.id}/edit`); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Activity could not be saved.'); } finally { setSaving(false); } };
  const assignOpen = async (activity: QuizActivity) => { try { setClassrooms(await listTeacherClassrooms()); setAssigning(activity); setClassroomId(''); setAvailableFrom(''); setDueAt(''); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Classrooms could not be loaded.'); } };
  const assign = async (event: React.FormEvent) => { event.preventDefault(); if (!assigning || !classroomId) return; try { await assignActivity({ classroomId, quizId: assigning.id ?? '', availableFrom: availableFrom ? new Date(availableFrom).toISOString() : undefined, dueAt: dueAt ? new Date(dueAt).toISOString() : undefined, isPublished }); setAssigning(null); setMessage('Activity assigned to classroom.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Assignment failed.'); } };
  const remove = async (activity: QuizActivity) => { if (!activity.id || !window.confirm(`Delete “${activity.title}”?`)) return; try { await deleteQuizActivity(activity.id); setMessage('Activity deleted.'); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Activity could not be deleted.'); } };
  const validQuestions = draft?.questions.every(q => q.question_text.trim() && Number.isInteger(q.points) && q.points > 0 && ((q.question_type === 'multiple_choice' || q.question_type === 'bond_type') ? (q.options ?? []).filter(o => o.trim()).length >= 2 && (q.options ?? []).includes(q.correct_answer) : q.question_type === 'true_false' ? ['True','False'].includes(q.correct_answer) : q.correct_answer.trim())) ?? false;
  if (busy) return <main className="teacher-builder-shell"><p role="status">Loading activities…</p></main>;
  if (!isEditor) return <main className="teacher-builder-shell"><div className="teacher-builder-topbar"><div><span className="eyebrow">TEACHER PORTAL</span><h1>My Activities</h1></div><button className="primary" onClick={() => navigate('/teacher/activities/new')}>+ Create Activity</button></div>{error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}{items.map(activity => <article className="activity-list-item builder-card" key={activity.id}><div><h2>{activity.title}</h2><p>{activity.description || 'No description'} · {activity.category} · {activity.difficulty}</p><p>{activity.total_questions} questions · {Math.round((activity.time_limit_seconds ?? 0)/60)} min · {activity.is_published ? 'Published' : 'Draft'} · Updated {activity.updated_at ? new Date(activity.updated_at).toLocaleDateString() : 'recently'}</p></div><div className="builder-actions"><button className="secondary" onClick={() => navigate(`/teacher/activities/${activity.id}/edit`)}>Edit</button><button className="secondary" onClick={() => { setDraft(activity); setPreview(true); }}>Preview</button><button className="secondary" onClick={() => void assignOpen(activity)}>Assign</button><button className="secondary" onClick={() => void remove(activity)}>Delete</button></div></article>)}{!items.length && <section className="empty-state-card"><h2>No activities yet</h2><p>Create a draft and add chemistry questions when ready.</p></section>}</main>;
  if (!draft) return <main className="teacher-builder-shell"><p role="alert">Activity could not be loaded.</p><button className="secondary" onClick={() => navigate('/teacher/activities')}>Back to activities</button></main>;
  return <main className="teacher-builder-shell"><div className="teacher-builder-topbar"><div><span className="eyebrow">ACTIVITY BUILDER</span><h1>{draft.title || 'New activity'}</h1></div><div className="builder-actions"><button className="secondary" onClick={() => navigate('/teacher/activities')}>Back</button><button className="secondary" onClick={() => setPreview(true)}>Preview</button><button className="secondary" disabled={saving} onClick={() => void save(false)}>Save Draft</button><button className="primary" disabled={saving || !draft.questions.length || !validQuestions} onClick={() => void save(true)}>Publish</button></div></div>
    {error && <p className="form-message error" role="alert">{error}</p>}{message && <p className="form-message success" role="status">{message}</p>}
    <div className="builder-editor-grid"><section className="builder-card"><h2>Activity information</h2><label><span>Title</span><input required value={draft.title} onChange={event => update('title', event.target.value)}/></label><label><span>Description</span><textarea rows={3} value={draft.description} onChange={event => update('description', event.target.value)}/></label><label><span>Instructions</span><textarea rows={3} value={draft.instructions ?? ''} onChange={event => update('instructions', event.target.value)}/></label><label><span>Category</span><select value={draft.category} onChange={event => update('category', event.target.value as ActivityCategory)}><option value="bonding">Chemical Bonding</option><option value="lewis_structures">Lewis Structures</option><option value="periodic_table">Periodic Table</option><option value="reactions">Reactions</option><option value="general">General Chemistry</option></select></label><div className="builder-two-col"><label><span>Difficulty</span><select value={draft.difficulty} onChange={event => update('difficulty', event.target.value as ActivityDifficulty)}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label><span>Time limit (minutes)</span><input type="number" min="1" value={Math.round((draft.time_limit_seconds ?? 900)/60)} onChange={event => update('time_limit_seconds', Math.max(1, Number(event.target.value))*60)}/></label></div><p>Status: {draft.is_published ? 'Published' : 'Draft'}</p></section>
    <section className="builder-card"><div className="builder-card-header"><h2>Questions ({draft.questions.length})</h2><button className="secondary" onClick={() => update('questions', [...draft.questions, freshQuestion(draft.questions.length+1)])}>+ Add Question</button></div>{draft.questions.map((question,index) => <article className="question-editor-block" key={question.id ?? index}><div className="question-editor-header"><strong>Q{index+1}</strong><button className="link-button" onClick={() => update('questions', draft.questions.filter((_,i) => i !== index).map((q,i) => ({...q,question_order:i+1})))}>Delete</button></div><label><span>Question type</span><select value={question.question_type} onChange={event => updateQuestion(index,'question_type',event.target.value as TeacherQuestionType)}>{questionTypes.map(type => <option value={type} key={type}>{type.replaceAll('_',' ')}</option>)}</select></label><label><span>Question</span><textarea required rows={3} value={question.question_text} onChange={event => updateQuestion(index,'question_text',event.target.value)}/></label>{['multiple_choice','bond_type'].includes(question.question_type) && <><label><span>Options (one per line)</span><textarea rows={4} value={(question.options ?? []).join('\n')} onChange={event => updateQuestion(index,'options',event.target.value.split('\n'))}/></label><label><span>Correct answer</span><select value={question.correct_answer} onChange={event => updateQuestion(index,'correct_answer',event.target.value)}><option value="">Select correct answer</option>{(question.options ?? []).filter(v => v.trim()).map((option,i) => <option key={`${option}-${i}`}>{option}</option>)}</select></label></>}{question.question_type === 'true_false' && <label><span>Correct answer</span><select value={question.correct_answer} onChange={event => updateQuestion(index,'correct_answer',event.target.value)}><option value="">Select answer</option><option>True</option><option>False</option></select></label>}{!['multiple_choice','bond_type','true_false'].includes(question.question_type) && <label><span>Correct answer</span><input value={question.correct_answer} onChange={event => updateQuestion(index,'correct_answer',event.target.value)}/></label>}<label><span>Points</span><input type="number" min="1" value={question.points} onChange={event => updateQuestion(index,'points',Number(event.target.value))}/></label><label><span>Hint</span><input value={question.hint} onChange={event => updateQuestion(index,'hint',event.target.value)}/></label><label><span>Explanation</span><textarea rows={2} value={question.explanation} onChange={event => updateQuestion(index,'explanation',event.target.value)}/></label></article>)}</section></div>
    {preview && <div className="modal-backdrop"><section className="builder-card assignment-dialog" role="dialog" aria-modal="true"><h2>Preview: {draft.title || 'Untitled activity'}</h2><p>{draft.description}</p>{draft.questions.map((question,index) => <article key={index}><strong>Q{index+1}. {question.question_text || 'Question text'}</strong><ul>{(question.options ?? []).filter(Boolean).map((option,i) => <li key={i}>{option}</li>)}</ul></article>)}<button className="secondary" onClick={() => setPreview(false)}>Close preview</button></section></div>}
    {assigning && <div className="modal-backdrop"><form className="builder-card assignment-dialog" role="dialog" aria-modal="true" onSubmit={assign}><h2>Assign {assigning.title}</h2><label><span>Classroom</span><select required value={classroomId} onChange={event => setClassroomId(event.target.value)}><option value="">Choose a classroom</option>{classrooms.map(room => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><label><span>Available from (optional)</span><input type="datetime-local" value={availableFrom} onChange={event => setAvailableFrom(event.target.value)}/></label><label><span>Due date (optional)</span><input type="datetime-local" value={dueAt} onChange={event => setDueAt(event.target.value)}/></label><label className="toggle-row"><input type="checkbox" checked={isPublished} onChange={event => setIsPublished(event.target.checked)}/><span>Publish assignment</span></label><div className="builder-actions"><button type="button" className="secondary" onClick={() => setAssigning(null)}>Cancel</button><button className="primary">Assign Activity</button></div></form></div>}
  </main>;
}
