import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import AppRoutes from './AppRoutes';
import { AuthProvider } from './lib/AuthContext';
import './styles.css';
import './custom.css';
import './chemlab-system.css';
import './chemsim-controls.css';
import './modal.css';
import './compound-visual.css';
import './shell-simulation.css';
import './lewis-structure.css';
import './simulator-responsive.css';
createRoot(document.getElementById('root')!).render(<StrictMode><AuthProvider><AppRoutes /></AuthProvider></StrictMode>);
